version: "3"
services:
  usermysql:
    image: mysql:latest
    container_name: bmdm
    ports:
      - 30000:30000
    environment:
      - MYSQL_ROOT_PASSWORD=bmdm
      - MYSQL_TCP_PORT=30000
      - TZ=Asia/Seoul
    command:
      [
        "mysqld",
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  redis:
    image: redis:latest
    command: redis-server
    container_name: redis_service
    hostname: redis_service
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 12621:6379